### ISSUE TITLE
slam

### ISSUE THREAD

**Issue by wmh02240** [bairuofei/Graph-Based_SLAM-Aware_Exploration#2]
作者您好，slam部分可以替换为cartographer算法吗？

**Comment by bairuofei** [comment]
Hi, thanks for your interest in our work. 

This repo is developed on the basis of [navigation_2d](https://github.com/skasperski/navigation_2d), where we mainly rewrite an exploration strategy plugin to the navigation_2d package, and we remain the SLAM part unchanged. By default, the navigatin_2d uses Karto as the SLAM implementation.  

So to replace Karto with cartographer, you can refer to the documents of the navigation_2d package. Maybe you can replace it by just remapping some topics from cartographer to those required by the navigation_2d. Hope this helps.

**Comment by wmh02240** [comment]
Okay，thanks for your reply。
