### ISSUE TITLE
catkin_make时出现问题，找不到cpp_solver/posegraph.h

### ISSUE THREAD

**Issue by eviaaan** [bairuofei/Graph-Based_SLAM-Aware_Exploration#3]
![b7698ebfd87eee28d6f5a6b50318311d](https://github.com/user-attachments/assets/0eb8e64c-2d10-4cb7-949a-751ff6e8b4df)

**Comment by bairuofei** [comment]
Hi, I run a quick test, and cannot reproduce your problem. Can you try to source ~/catkin_ws/devel/setup.bash before catkin_make? If the error still exists, you can try to remove the package and git clone again. Let me know whether it works.

**Comment by eviaaan** [comment]
Sorry，I just git clone again and do remember to source this time.But the same error occured，I dont understand.

**Comment by eviaaan** [comment]
omg it works finally！ i didnt git clone but download it and unzip. And I forgot to extract it from the parent directory. HaHa.
